import { defineConfig } from 'vite-plus'

export default defineConfig({
	staged: {
		'[!.]*.{js,jsx,ts,tsx,cjs,mjs,mts,cts}':
			'vp check --fix --no-error-on-unmatched-pattern',
		'[!.]*.{json,jsonc,json5,md,mdx,markdown,yaml,yml,css,less,scss,html,gql,graphql,hbs,handlebars,vue}':
			'vp fmt --no-error-on-unmatched-pattern',
	},
	run: {
		tasks: {
			test: {
				command: 'vp test',
				input: [
					'vite.config.ts',
					'vitest.config.ts',
					'package.json',
					'pnpm-workspace.yaml',
					'apps/**/src/**/*.{js,ts,jsx,tsx}',
					'packages/**/src/**/*.{js,ts,jsx,tsx}',
				],
				cache: true,
			},
			'test:coverage': {
				command: 'vp test run --coverage',
				input: [
					'vite.config.ts',
					'vitest.config.ts',
					'package.json',
					'pnpm-workspace.yaml',
					'apps/**/src/**/*.{js,ts,jsx,tsx}',
					'packages/**/src/**/*.{js,ts,jsx,tsx}',
				],
				cache: true,
			},
			tsc: {
				command: 'vpr -r tsc',
			},
			knip: {
				command: 'knip --cache',
			},
			commitlint: {
				command: 'commitlint --edit',
			},
			verify_ci: {
				command: 'vpr knip && vpr tsc && vpr test',
			},
			verify_pre: {
				command: 'vpr knip && vpr tsc && vpr test --changed',
			},
			ci: {
				command: 'vp check && vpr -r build && vpr --parallel verify_ci',
			},
		},
	},
	test: {
		coverage: {
			exclude: ['**/*.test.*'],
			include: ['**/src/**/*.{js,ts,jsx,tsx}'],
			provider: 'v8',
			reporter: ['text', 'json'],
			thresholds: {
				// branches: 100,
				// functions: 100,
				// lines: 100,
				// statements: 100,
			},
		},
		environment: 'happy-dom',
		globals: true,
		include: ['**/src/**/*.test.{js,ts,jsx,tsx}'],
	},
	fmt: {
		arrowParens: 'always',
		ignorePatterns: ['.*'],
		jsxSingleQuote: true,
		printWidth: 80,
		semi: false,
		singleQuote: true,
		sortPackageJson: false,
		trailingComma: 'all',
		useTabs: true,
	},
	lint: {
		ignorePatterns: ['.*'],
		options: {
			typeAware: true,
			denyWarnings: true,
		},
		plugins: ['typescript', 'react'],
		settings: {
			react: {
				version: '19.2.3',
			},
		},
		categories: {
			correctness: 'off',
		},
		env: {
			builtin: true,
		},
		rules: {
			'no-array-constructor': 'error',
			'no-unused-expressions': 'error',
			'constructor-super': 'error',
			'for-direction': 'error',
			'no-async-promise-executor': 'error',
			'no-case-declarations': 'error',
			'no-class-assign': 'error',
			'no-compare-neg-zero': 'error',
			'no-cond-assign': 'error',
			'no-const-assign': 'error',
			'no-constant-binary-expression': 'error',
			'no-constant-condition': 'error',
			'no-control-regex': 'error',
			'no-debugger': 'error',
			'no-delete-var': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-else-if': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-empty-character-class': 'error',
			'no-empty-pattern': 'error',
			'no-empty-static-block': 'error',
			'no-ex-assign': 'error',
			'no-extra-boolean-cast': 'error',
			'no-fallthrough': 'error',
			'no-func-assign': 'error',
			'no-global-assign': 'error',
			'no-import-assign': 'error',
			'no-invalid-regexp': 'error',
			'no-irregular-whitespace': 'error',
			'no-loss-of-precision': 'error',
			'no-misleading-character-class': 'error',
			'no-new-native-nonconstructor': 'error',
			'no-nonoctal-decimal-escape': 'error',
			'no-obj-calls': 'error',
			'no-prototype-builtins': 'error',
			'no-regex-spaces': 'error',
			'no-self-assign': 'error',
			'no-setter-return': 'error',
			'no-shadow-restricted-names': 'error',
			'no-sparse-arrays': 'error',
			'no-this-before-super': 'error',
			'no-unassigned-vars': 'error',
			'no-unexpected-multiline': 'error',
			'no-unsafe-finally': 'error',
			'no-unsafe-negation': 'error',
			'no-unsafe-optional-chaining': 'error',
			'no-unused-labels': 'error',
			'no-unused-private-class-members': 'error',
			'no-useless-backreference': 'error',
			'no-useless-catch': 'error',
			'no-useless-escape': 'error',
			'no-with': 'error',
			'preserve-caught-error': 'error',
			'require-yield': 'error',
			'use-isnan': 'error',
			'valid-typeof': 'error',
			'typescript/ban-ts-comment': 'error',
			'typescript/no-duplicate-enum-values': 'error',
			'typescript/await-thenable': 'error',
			'typescript/no-extra-non-null-assertion': 'error',
			'typescript/no-floating-promises': 'error',
			'typescript/no-misused-new': 'error',
			'typescript/no-misused-promises': 'error',
			'typescript/no-namespace': 'error',
			'typescript/no-non-null-asserted-optional-chain': 'error',
			'typescript/no-require-imports': 'error',
			'typescript/no-this-alias': 'error',
			'typescript/no-unnecessary-type-constraint': 'error',
			'typescript/no-unsafe-argument': 'off',
			'typescript/no-unsafe-assignment': 'off',
			'typescript/no-unsafe-call': 'off',
			'typescript/no-unsafe-declaration-merging': 'error',
			'typescript/no-unsafe-function-type': 'error',
			'typescript/no-unsafe-member-access': 'off',
			'typescript/no-unsafe-return': 'off',
			'typescript/prefer-as-const': 'error',
			'typescript/prefer-namespace-keyword': 'error',
			'typescript/triple-slash-reference': 'error',
			'no-console': 'error',
			'no-else-return': 'error',
			'no-empty': 'error',
			'no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
				},
			],
			'no-useless-rename': ['error'],
			'object-shorthand': ['error', 'always'],
			'typescript/no-empty-object-type': 'off',
			'typescript/no-explicit-any': 'off',
			'no-var': 'error',
			'prefer-const': 'error',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'no-redeclare': 'off',
		},
		overrides: [
			{
				files: [
					'apps/**/*.{js,jsx,ts,tsx}',
					'packages/react/**/*.{js,jsx,ts,tsx}',
				],
				rules: {
					'react/exhaustive-deps': 'error',
					'react/rules-of-hooks': 'error',
				},
			},
			{
				files: ['**/*.{jsx,tsx}'],
				rules: {
					'react/button-has-type': 'error',
					'react/jsx-key': 'error',
					'react/jsx-no-duplicate-props': 'error',
					'react/jsx-no-target-blank': 'error',
					'react/jsx-no-undef': 'error',
					'react/no-children-prop': 'error',
					'react/no-danger-with-children': 'error',
					'react/no-unknown-property': 'error',
					'react/void-dom-elements-no-children': 'error',
				},
			},
		],
	},
})
